sudo: false
language: node_js
node_js:
  - "5.10.1"
notifications:
  irc:
    channels:
      - "irc.mozilla.org#l20n"
    on_success: always
    on_failure: always
    use_notice: true
    template:
      - "#%{build_number} %{message} %{build_url}"
      - "Change by %{author}: %{compare_url}"
