name: "@fluent/langneg"
on: [push, pull_request]
jobs:
  dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{matrix.node}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - name: Install build tools
        run: npm ci
      - name: Install package dependencies
        working-directory: ./fluent-langneg
        run: npm ci
      - name: make dist
        working-directory: ./fluent-langneg
        run: make dist
